# Generated by Django 3.1.7 on 2021-04-30 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='filename',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
